var HOME_I18N_ZH = {
  'nav.dev':'开发中',
  'nav.support':'联系支持',
  'hero.eyebrow':'致敬《死亡搁浅》与《大灾变：黑暗降临》',
  'hero.tagline':'行走在送货的路上，步入危险之地',
  'hero.scroll':'向下滚动',
  'gallery.eyebrow':'画廊',
  'gallery.h2':'实机画面',
  'gallery.soon':'即将上线',
  'pitch.eyebrow':'幸存者手册',
  'pitch.h2':'G市',
  'pitch.p1':'你叫 Sam，一名信使。红雾从小镇外沿升起那天开始，这里就成了危险之地——路还在，房子还在，只是大家都变成了焦油人。你为剩下的人运送物资，肩上很快会架起一座越叠越高的<strong>货塔</strong>：物资、零件、最后一口口粮都是生存的关键。',
  'pitch.p2':'饥饿、口渴、疲劳都是真实需求，气味和噪音会暴露你。穿过街道，找到你的出路——或者，找到那个仍愿意伸手连接你的人。',
  'pitch.platform':'平台 — 现已登陆 Steam',
  'pitch.cta':'进入幸存者手册 →',
  'pillar.1.title':'救赎',
  'pillar.1.desc':'这个世界需要救赎，而非毁灭。',
  'pillar.2.title':'吸收',
  'pillar.2.desc':'沉重的代价。',
  'pillar.3.title':'连接',
  'pillar.3.desc':'从绳索到桥梁：用连接重新缝合断裂的世界。',
  'closing.h2':'危险，仍在等你。',
  'closing.sub':'《Sponge Bridges》目前正在开发中。',
  'closing.notify':'敬请期待'
};
