var HOME_I18N_EN = {
  'nav.dev': 'In Development',
  'cta.wishlist': 'Wishlist on Steam',
  'nav.news': 'News',
  'nav.support': 'Contact Support',
  'hero.eyebrow': '',
  'hero.tagline': 'Walk the path of delivery into treacherous lands.',
  'hero.scroll': 'Scroll Down',
  'news.h2': 'Latest News',
  'news.all': 'All announcements →',
  'news.date': 'October 3, 2026',
  'news.tag': 'Kickstarter',
  'news.title': 'Sponge Bridges is now on Kickstarter!',
  'news.summary': 'Support the game and help make its world richer.',
  'news.m1.when': 'Oct 1, 2026',
  'news.m1.what': 'Demo v0.1',
  'news.m2.when': 'Nov 1, 2026',
  'news.m2.what': 'Early Access Beta Testing',
  'news.m3.when': 'Dec 2026',
  'news.m3.what': 'Early Access',
  'news.m4.when': 'Dec 2027',
  'news.m4.what': 'Version 1.0',
  'news.read': 'Read the announcement →',
  'gallery.eyebrow': 'Gallery',
  'gallery.h2': 'Gameplay Screenshots',
  'gallery.soon': 'Coming Soon',
  'pitch.eyebrow': 'Survivor\'s Dossier',
  'pitch.h2': 'G-City',
  'pitch.p1':'G-City has fallen. Survivors are hiding in scattered corners of the city, and food, and everyday supplies are scarce. You make a living delivering cargo for others—and, along the way, try to find out what happened here. For now... just get the cargo delivered. And try not to starve on the way.',
  'pitch.p2':'Sponge Bridges is a delivery-focused post-apocalyptic survival game paying homage to Death Stranding and Cataclysm: Dark Days Ahead. An anomalous substance from deep space descended upon the world, swallowing surface civilization like a tide. A handful of survivors are scattered among the scorched ruins. You are a courier. The cargo on your back is the only thing still connecting these worlds. And at the far end of all this danger, the source of the apocalypse seems to be waiting. Find it, and perhaps you can save this world. In this dangerous world, It may decide whether an entire city is destroyed by a nuclear strike. So, one piece after another— keep stacking it higher.',
  'pitch.platform': 'Platform — Out now on Steam',
  'pitch.cta': 'Access DEMO Dossier →',
  'pillar.1.title': 'Redemption',
  'pillar.1.desc': 'This world needs more redemption, not destruction.',
  'pillar.2.title': 'Survival',
  'pillar.2.desc': 'Survival is the currency of your journey.',
  'pillar.3.title': 'Connection',
  'pillar.3.desc': 'From ropes to bridges: stitch a broken world back together through connection.',
  'crowd.live': '',
  'crowd.h2': 'On Kickstarter, you can become part of this world',
  'crowd.sub': 'Backing is not only more time to keep building. Feedback, ideas, professions, appearances, stories, and custom NPCs can all end up in the world of Sponge Bridges.',
  'roadmap.eyebrow': 'Roadmap',
  'roadmap.h2': 'Where this goes next',
  'roadmap.s0.flag': 'Out now',
  'roadmap.s0.when': 'Oct 1, 2026',
  'roadmap.s0.what': 'Demo v0.1',
  'roadmap.s0.note': 'The first public version of Sponge Bridges.',
  'roadmap.s1.flag': 'Up next',
  'roadmap.s1.when': 'Nov 1, 2026',
  'roadmap.s1.what': 'Early Access Beta Testing',
  'roadmap.s1.note': 'The next major step, with more content, systems, items, locations, and progression available for testing.',
  'roadmap.s2.when': 'Dec 2026',
  'roadmap.s2.what': 'Early Access',
  'roadmap.s2.note': 'Sponge Bridges officially enters Early Access.',
  'roadmap.s3.when': 'Dec 2027',
  'roadmap.s3.what': 'Version 1.0',
  'roadmap.s3.note': 'The planned full release of Sponge Bridges.',
  'roadmap.thanks': 'Thanks for being here this early.',
  'roadmap.cta': 'Wishlist <strong>Sponge Bridges</strong> and follow the game to keep up with development.',
  'community.eyebrow': 'Community',
  'community.h2': 'Come talk about it',
  'community.sub': 'Questions, ideas, bug reports, or just what happened on your last run — the Steam discussion board is where it all goes.',
  'community.qq': '',
  'community.cta': 'Steam Discussions',
  'closing.h2': 'Danger still awaits you.',
  'closing.sub': 'Sponge Bridges is currently in development.',
  'closing.notify': 'Stay Tuned'
};
