var HOME_I18N_EN = {
  'nav.dev':'In Development',
  'nav.support':'Contact Support',
  'hero.eyebrow':'A Tribute to DEATH STRANDING & Cataclysm: DDA',
  'hero.tagline':'Walking the delivery road, stepping into danger.',
  'hero.scroll':'Scroll',
  'gallery.eyebrow':'Gallery',
  'gallery.h2':'In-Engine Footage',
  'gallery.soon':'Coming soon',
  'pitch.eyebrow':'Survivor’s Handbook',
  'pitch.h2':'G City',
  'pitch.p1':'You are Sam, a courier. The day the fog rose past the edge of town, it became a danger zone — the roads are still there, the houses are still there, it’s just everyone in them turned to tar. You still haul goods and supplies for the people who are left; soon there’s a tall tower stacked on your back — supplies, spare parts, rations — all of it matters for survival.',
  'pitch.p2':'Hunger, thirst, and fatigue are real needs. Scent and noise really do give you away. Cross the streets and find your own way out — or find the one person still willing to connect with you.',
  'pitch.platform':'Platform — Now on Steam',
  'pitch.cta':'Enter the Survivor’s Handbook →',
  'pillar.1.title':'Redemption',
  'pillar.1.desc':'This world needs redemption, not destruction.',
  'pillar.2.title':'Absorb',
  'pillar.2.desc':'A heavy price.',
  'pillar.3.title':'Connect',
  'pillar.3.desc':'From rope to bridge: mending a broken world through connection.',
  'closing.h2':'Danger is waiting.',
  'closing.sub':'Sponge Bridges is currently in development.',
  'closing.notify':'More to come'
};
