var HOME_I18N_ZH = {
  'nav.dev':'开发中',
  'cta.wishlist':'加入 Steam 愿望单',
  'nav.news':'公告',
  'nav.support':'联系支持',
  'hero.eyebrow':'',
  'hero.tagline':'行走在送货的路上，步入危险之地',
  'hero.scroll':'向下滚动',
  'news.h2':'最新公告',
  'news.all':'全部公告 →',
  'news.date':'2026 年 10 月 3 日',
  'news.tag':'众筹',
  'news.title':'Sponge Bridges 现已登陆 Kickstarter！',
  'news.summary':'支持游戏，也一起让这个世界变得更加丰富。',
  'news.m1.when':'2026.10.01',
  'news.m1.what':'Demo v0.1',
  'news.m2.when':'2026.11.01',
  'news.m2.what':'抢先体验 Beta 测试',
  'news.m3.when':'2026.12',
  'news.m3.what':'抢先体验',
  'news.m4.when':'2027.12',
  'news.m4.what':'1.0 正式版',
  'news.read':'阅读全文 →',
  'gallery.eyebrow':'画廊',
  'gallery.h2':'实机画面',
  'gallery.soon':'即将上线',
  'pitch.eyebrow':'幸存者手册',
  'pitch.h2':'G市',
  'pitch.p1':'你所在的 G 市已经沦陷。街道被遗弃，幸存者各自躲在城市不同的角落，食物、药品和日用品都成了稀缺品。你靠替人运送货物活下去，也顺便看看这座城市到底发生了什么。总之……先把货送到。以及……尽量别饿死在路上。',
  'pitch.p2':'《Sponge Bridges》是一款致敬《死亡搁浅》与《大灾变：黑暗降临》的送货式末日生存游戏。 自深空降临的异态物质，如潮水般吞没了一切地表文明。少数幸存者散落在化为焦土的废墟中。 你是一名信使。你背上的货物，是世界之间唯一还连着的东西。 而在危险的尽头，似乎隐藏着这场末日的源头。 找到它，也许就能拯救这个世界。',
  'pitch.platform':'平台 — 现已登陆 Steam',
  'pitch.cta':'进入DEMO版本手册 →',
  'pillar.1.title':'救赎',
  'pillar.1.desc':'这个世界需要更多救赎，而非毁灭。',
  'pillar.2.title':'生存',
  'pillar.2.desc':'生存是你行动的资本。',
  'pillar.3.title':'连接',
  'pillar.3.desc':'从绳索到桥梁：用连接重新缝合断裂的世界。',
  'crowd.live':'众筹进行中',
  'crowd.h2':'在 Kickstarter 上，你可以成为这个世界的一部分',
  'crowd.sub':'众筹不只是让我有更多时间把游戏做下去。反馈、想法、职业、外观、故事，还有定制 NPC —— 都有机会留在《Sponge Bridges》的世界里。',
  'roadmap.eyebrow':'开发路线图',
  'roadmap.h2':'接下来往哪走',
  'roadmap.s0.flag':'现已发布',
  'roadmap.s0.when':'2026.10.01',
  'roadmap.s0.what':'Demo v0.1',
  'roadmap.s0.note':'Sponge Bridges 的首个公开版本。',
  'roadmap.s1.flag':'下一站',
  'roadmap.s1.when':'2026.11.01',
  'roadmap.s1.what':'抢先体验 Beta 测试',
  'roadmap.s1.note':'下一阶段的重要测试版本，将开放更多内容、系统、物品、地点和成长内容进行测试。',
  'roadmap.s2.when':'2026.12',
  'roadmap.s2.what':'抢先体验',
  'roadmap.s2.note':'Sponge Bridges 正式进入抢先体验阶段。',
  'roadmap.s3.when':'2027.12',
  'roadmap.s3.what':'Version 1.0',
  'roadmap.s3.note':'计划发布 Sponge Bridges 正式版。',
  'roadmap.thanks':'感谢你这么早就来到这里。',
  'roadmap.cta':'如果你喜欢这个 Demo，欢迎将《<strong>Sponge Bridges</strong>》加入愿望单，并关注游戏后续开发进度。',
  'community.eyebrow':'社区',
  'community.h2':'来聊聊',
  'community.sub':'有疑问、有点子、发现了问题，或者只是想讲讲这一趟送货是怎么翻车的 —— 都可以去 Steam 讨论区。',
  'community.qq':'玩家交流 QQ 群 <b>437182032</b>',
  'community.cta':'Steam 讨论区',
  'closing.h2':'危险，仍在等你。',
  'closing.sub':'《Sponge Bridges》目前正在开发中。',
  'closing.notify':'敬请期待'
};
