var NEWS_I18N_EN = {
  'page.doctitle':'News & Updates — Sponge Bridges',
  'nav.phil':'Philosophy',
  'nav.back':'← Home',
  'cta.wishlist':'Wishlist on Steam',

  'page.eyebrow':'Development News',
  'page.title':'News',
  'page.lede':'Announcements posted to the Steam page, collected here.',

  'p3.date':'October 3, 2026',
  'p3.tag':'Kickstarter',
  'p3.title':'Sponge Bridges is now on Kickstarter!',
  'p3.subtitle':'More development time, more ways for players to become part of the world.',
  'p3.body1':'Sponge Bridges is now on Kickstarter!',
  'p3.body2':'Kickstarter can give me more time to work on the game, but I also want it to become another way for players to take part in its development.',
  'p3.body3':'Feedback, ideas, professions, appearances, stories, and custom NPCs can all help make the world of Sponge Bridges richer and more varied.',
  'p3.body4':'If you\'d like to support the project — or even leave a small part of yourself in the game — you can join the campaign here:',
  'p3.thanks':'Thank you for helping me build this world together with you!',

  'p2.date':'October 1, 2026',
  'p2.tag':'Release',
  'p2.title':'Sponge Bridges Demo v0.1 is now available!',
  'p2.subtitle':'The first public demo is now live.',
  'p2.body1':'Sponge Bridges Demo v0.1 is now available!',
  'p2.body2':'Welcome to the first public release.',
  'p2.body3':'If you run into bugs or have any feedback, feel free to let me know in the Steam Community Discussions.',
  'p2.join':'Join the community',
  'p2.link1.when':'Steam Community Discussions',
  'p2.link1.what':'Bugs, feedback, and everything else',
  'p2.link2.when':'QQ group',
  'p2.link2.what':'437182032',
  'p2.thanks':'Thanks for playing!',

  'p1.date':'September 29, 2026',
  'p1.tag':'Announcement',
  'p1.title':'Sponge Bridges Demo v0.1 — Coming October 1!',
  'p1.subtitle':'The first public demo is almost here. Welcome to the world of Sponge Bridges.',

  'p1.hello1':'Hey everyone — I\'m Alun, welcome to Sponge Bridges.',
  'p1.hello2':'The first public demo is almost here, and this is the first time I\'m properly saying hello to all of you.',

  'p1.body1':'<strong>Sponge Bridges Demo v0.1 is planned to launch on October 1, 2026.</strong>',
  'p1.body1b':'Yes, indeed.',
  'p1.body2':'In a dangerous and lonely post-apocalyptic world.',
  'p1.beat1':'Deliver cargo',
  'p1.beat2':'Scavenge',
  'p1.beat3':'Survive',
  'p1.beat4':'Fight',
  'p1.body3':'And one day, find a way to reconnect what was lost.',
  'p1.body4':'This is just the beginning. I\'ll continue updating and improving the demo as we head into <strong>Steam Next Fest — October 2026</strong>.',

  'p1.roadmap':'Roadmap',
  'p1.r1.when':'October 1, 2026 — Demo v0.1',
  'p1.r1.what':'The first public version of Sponge Bridges.',
  'p1.r2.when':'November 1, 2026 — Early Access Beta Testing',
  'p1.r2.what':'The next major step, with more content, systems, items, locations, and progression available for testing.',
  'p1.r3.when':'December 2026 — Early Access',
  'p1.r3.what':'Sponge Bridges officially enters Early Access.',
  'p1.r4.when':'December 2027 — Version 1.0',
  'p1.r4.what':'The planned full release of Sponge Bridges.',

  'p1.thanks':'Thanks for being here this early.',
  'p1.cta':'Wishlist <strong>Sponge Bridges</strong> and follow the game to keep up with development.'
};
