var NEWS_I18N_ZH = {
  'nav.phil':'理念',
  'nav.back':'← 返回首页',
  'cta.wishlist':'加入 Steam 愿望单',

  'page.eyebrow':'开发公告',
  'page.title':'公告',
  'page.lede':'发布在 Steam 页面上的公告，都会同步收在这里。',

  'p3.date':'2026 年 10 月 3 日',
  'p3.tag':'众筹',
  'p3.title':'Sponge Bridges 现已登陆 Kickstarter！',
  'p3.subtitle':'更多开发时间，也让玩家真正成为这个世界的一部分。',
  'p3.body1':'Sponge Bridges 现已登陆 Kickstarter！',
  'p3.body2':'Kickstarter 不仅能让我投入更多时间开发游戏，我也希望它能成为玩家参与开发的另一种方式。',
  'p3.body3':'反馈、想法、职业、外观、故事，以及定制 NPC，都有机会让 Sponge Bridges 的世界变得更加丰富和多样。',
  'p3.body4':'如果你愿意支持这个项目，甚至在游戏世界里留下一点属于自己的东西，可以在这里参与众筹：',
  'p3.thanks':'感谢大家和我一起把这个世界慢慢做出来！',

  'p2.date':'2026 年 10 月 1 日',
  'p2.tag':'发布',
  'p2.title':'Sponge Bridges 试玩版 v0.1 现已上线！',
  'p2.subtitle':'首个公开试玩版现已推出。',
  'p2.body1':'Sponge Bridges 试玩版 v0.1 现已发布！',
  'p2.body2':'欢迎体验首个公开版本。',
  'p2.body3':'如果您在游玩过程中遇到任何 Bug，或有任何反馈建议，欢迎在 Steam 社区讨论区中告诉我。',
  'p2.join':'加入社区与获取更多资讯',
  'p2.link1.when':'Steam 社区讨论区',
  'p2.link1.what':'Bug、反馈，以及其他一切',
  'p2.link2.when':'玩家交流 QQ 群',
  'p2.link2.what':'437182032',
  'p2.thanks':'感谢您的游玩！',

  'p1.date':'2026 年 9 月 29 日',
  'p1.tag':'公告',
  'p1.title':'海绵桥《Sponge Bridges》Demo v0.1 — 预计 10 月 1 日发布！',
  'p1.subtitle':'首个公开 Demo 即将到来。欢迎来到 Sponge Bridges 的世界。',

  'p1.hello1':'大家好 —— 我是 Alun，欢迎来到海绵桥《Sponge Bridges》。',
  'p1.hello2':'首个公开 Demo 很快就要和大家见面了，这也是我第一次正式和大家打个招呼。',

  'p1.body1':'<strong>Sponge Bridges Demo v0.1 预计将于 2026 年 10 月 1 日发布。</strong>',
  'p1.body1b':'是的，没错。',
  'p1.body2':'在一个危机四伏、孤独的末日世界里。',
  'p1.beat1':'运送货物',
  'p1.beat2':'搜刮物资',
  'p1.beat3':'生存下去',
  'p1.beat4':'战斗',
  'p1.body3':'也许有一天，你还需要找到一种方式，重新连接那些失去联系的事物。',
  'p1.body4':'这仅仅只是开始。随着 <strong>Steam 新品节 — 2026 年 10 月</strong> 的临近，我会继续更新并完善 Demo。',

  'p1.roadmap':'开发路线图',
  'p1.r1.when':'2026 年 10 月 1 日 — Demo v0.1',
  'p1.r1.what':'Sponge Bridges 的首个公开版本。',
  'p1.r2.when':'2026 年 11 月 1 日 — 抢先体验 Beta 测试',
  'p1.r2.what':'下一阶段的重要测试版本，将开放更多内容、系统、物品、地点和成长内容进行测试。',
  'p1.r3.when':'2026 年 12 月 — 抢先体验',
  'p1.r3.what':'Sponge Bridges 正式进入抢先体验阶段。',
  'p1.r4.when':'2027 年 12 月 — Version 1.0',
  'p1.r4.what':'计划发布 Sponge Bridges 正式版。',

  'p1.thanks':'感谢你这么早就来到这里。',
  'p1.cta':'如果你喜欢这个 Demo，欢迎将 <strong>Sponge Bridges</strong> 加入愿望单，并关注游戏后续开发进度。'
};
