var HOME_I18N_ZH = {
  'nav.dev':'预备阶段',
  'nav.support':'联系支持',
  'hero.eyebrow':'致敬《死亡搁浅》与《大灾变：黑暗降临》',
  'hero.tagline':'每一步都是一次配送。每一次配送，都是你独自一人在浓雾中做出的选择——背上是你所有的一切。',
  'hero.scroll':'向下滚动',
  'gallery.eyebrow':'画廊',
  'gallery.h2':'游戏实机截图',
  'gallery.soon':'截图即将上线',
  'pitch.eyebrow':'幸存者手册',
  'pitch.h2':'G市',
  'pitch.p1':'你叫 Sam，一名信使。红雾从小镇外沿升起那天起，这里就成了无人区——路还在，房子还在，只是没人愿意再走进来。你背着一副货运骨架醒来，肩上很快会架起一座越叠越高的<strong>货物塔</strong>：物资、零件、最后一口口粮，重量和体积都实打实地算数。',
  'pitch.p2':'没有安全屋，没有传送点。饥饿、口渴、疲劳都是真实数值，气味和噪音会真正暴露你。穿过街道、公寓、警局与地下室，找到你的出路——修好去雾装置、炸开一道缺口、硬扛穿雾，或者找那个唯一愿意伸手的人。<em>四条路，谁先走通谁算数。</em>',
  'pitch.platform':'平台 — 仅 Steam',
  'pitch.cta':'进入幸存者手册 →',
  'pillar.1.title':'浸透',
  'pillar.1.desc':'扛得越多，吸得越透——重量是你自己选的代价。',
  'pillar.2.title':'吸收',
  'pillar.2.desc':'吸收，而非毁灭。',
  'pillar.3.title':'连接',
  'pillar.3.desc':'从绳索到桥梁：用连接重新缝合断裂的世界。',
  'closing.h2':'浓雾，仍在等你。',
  'closing.sub':'《Sponge Bridges》目前正在开发中。关注我们，一起等这场走出迷雾的旅程。',
  'closing.notify':'敬请期待'
};
