var HOME_I18N_EN = {
  'nav.dev':'In Development',
  'nav.support':'Contact Support',
  'hero.eyebrow':'A Tribute to DEATH STRANDING & Cataclysm: DDA',
  'hero.tagline':'Alone. Everything on your back. Walking the road anyway.',
  'hero.scroll':'Scroll',
  'gallery.eyebrow':'Gallery',
  'gallery.h2':'In-Engine Footage',
  'gallery.soon':'Coming soon',
  'pitch.eyebrow':'Survivor’s Handbook',
  'pitch.h2':'G City',
  'pitch.p1':'You are Sam, a courier. The day the fog rose past the edge of town, it became a danger zone — the roads are still there, the houses are still there, it’s just everyone in them turned to tar. You still run supplies for the people who are left; soon there’s a tower stacked higher with every haul — supplies, spare parts, your last ration — the weight and the bulk both count, for real.',
  'pitch.p2':'Hunger, thirst, and fatigue are real needs. Scent and noise really do give you away. Cross the streets and find your own way out — or find the ones still willing to connect.',
  'pitch.platform':'Platform — Now on Steam',
  'pitch.cta':'Enter the Survivor’s Handbook →',
  'pillar.1.title':'Soak',
  'pillar.1.desc':'The longer you soak, the deeper it goes — what even is weight, anymore?',
  'pillar.2.title':'Absorb',
  'pillar.2.desc':'Absorb, not destroy.',
  'pillar.3.title':'Connect',
  'pillar.3.desc':'From rope to bridge: mending a broken world through connection.',
  'closing.h2':'Danger is waiting.',
  'closing.sub':'Sponge Bridges is currently in development.',
  'closing.notify':'More to come'
};
