var HOME_I18N_EN = {
  'nav.dev':'Pre-Alpha',
  'nav.support':'Contact Support',
  'hero.eyebrow':'A Tribute to DEATH STRANDING & Cataclysm: DDA',
  'hero.tagline':'Every step is a delivery. Every delivery is a choice you make alone, in the fog, with everything you own strapped to your back.',
  'hero.scroll':'Scroll',
  'gallery.eyebrow':'Gallery',
  'gallery.h2':'Captured In-Engine',
  'gallery.soon':'Screenshots coming soon',
  'pitch.eyebrow':'Survivor’s Handbook',
  'pitch.h2':'G City',
  'pitch.p1':'You are Sam, a courier. The day the fog rose past the edge of town, it became no-man’s-land — the roads are still there, the houses are still there, nobody wants to walk in anymore. You wake strapped into a cargo frame; soon there’s a tower stacked higher with every haul — supplies, spare parts, your last ration — the weight and the bulk both count, for real.',
  'pitch.p2':'No safehouses. No waypoints. Hunger, thirst, and fatigue are real numbers. Scent and noise really do give you away. Cross the streets, the apartments, the precinct, the basements — find your own way out: fix the fog device, blast a gap through, walk it off, or find the one person still willing to help. <em>Four routes. First one you finish is the one that counts.</em>',
  'pitch.platform':'Platform — Steam Only',
  'pitch.cta':'Enter the Survivor’s Handbook →',
  'pillar.1.title':'Soaked Through',
  'pillar.1.desc':'The more you carry, the more you soak up — the weight is a cost you chose yourself.',
  'pillar.2.title':'Absorb',
  'pillar.2.desc':'Absorb, not destroy.',
  'pillar.3.title':'Connect',
  'pillar.3.desc':'From rope to bridge: mending a broken world through connection.',
  'closing.h2':'The fog is waiting.',
  'closing.sub':'Sponge Bridges is currently in development. Follow along for the walk out.',
  'closing.notify':'More to come'
};
